-- liquibase formatted sql

-- changeset toswim:002-criar-fn-updated-at splitStatements:false
-- comment: Cria funcao reutilizavel para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION fn_atualizar_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- rollback DROP FUNCTION IF EXISTS fn_atualizar_updated_at();

-- changeset toswim:002-criar-usuario
-- comment: Cria a tabela de usuarios
CREATE TABLE usuario (
    cod_usuario   INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    senha_hash    VARCHAR(255) NOT NULL,
    status_conta  SMALLINT     NOT NULL DEFAULT 1,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_usuario_status_conta
        CHECK (status_conta IN (0, 1))
);
-- rollback DROP TABLE IF EXISTS usuario;

-- changeset toswim:002-criar-trigger-usuario
-- comment: Cria trigger de atualizacao automatica do updated_at na tabela usuario
CREATE TRIGGER trg_usuario_updated_at
    BEFORE UPDATE ON usuario
    FOR EACH ROW
    EXECUTE FUNCTION fn_atualizar_updated_at();
-- rollback DROP TRIGGER IF EXISTS trg_usuario_updated_at ON usuario;