-- liquibase formatted sql

-- changeset toswim:003-criar-config-piscina
-- comment: Cria a tabela de configuracao da piscina do usuario
CREATE TABLE config_piscina (
    cod_piscina    INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_usuario    INT         NOT NULL,
    tamanho_m      SMALLINT    NOT NULL,
    forma_contagem SMALLINT    NOT NULL,
    status         SMALLINT    NOT NULL DEFAULT 1,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_config_piscina_usuario
        FOREIGN KEY (cod_usuario)
        REFERENCES usuario (cod_usuario),

    CONSTRAINT chk_config_piscina_tamanho
        CHECK (tamanho_m IN (25, 50)),

    CONSTRAINT chk_config_piscina_forma_contagem
        CHECK (forma_contagem IN (0, 1)),

    CONSTRAINT chk_config_piscina_status
        CHECK (status IN (0, 1)),

    CONSTRAINT uq_config_piscina_usuario
        UNIQUE (cod_usuario)
);
-- rollback DROP TABLE IF EXISTS config_piscina;

-- changeset toswim:003-criar-trigger-config-piscina
-- comment: Cria trigger de atualizacao automatica do updated_at na tabela config_piscina
CREATE TRIGGER trg_config_piscina_updated_at
    BEFORE UPDATE ON config_piscina
    FOR EACH ROW
    EXECUTE FUNCTION fn_atualizar_updated_at();
-- rollback DROP TRIGGER IF EXISTS trg_config_piscina_updated_at ON config_piscina;