-- liquibase formatted sql

-- changeset toswim:004-criar-ficha-base
-- comment: Cria a tabela de fichas base de treino
CREATE TABLE ficha_base (
    cod_ficha     INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_usuario   INT          NOT NULL,
    titulo_ficha  VARCHAR(120) NOT NULL,
    tipo_ficha    SMALLINT     NOT NULL DEFAULT 0,
    status        SMALLINT     NOT NULL DEFAULT 1,
    ficha_copiada INT          NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_ficha_base_usuario
        FOREIGN KEY (cod_usuario)
        REFERENCES usuario (cod_usuario),

    CONSTRAINT fk_ficha_base_copiada
        FOREIGN KEY (ficha_copiada)
        REFERENCES ficha_base (cod_ficha)
        ON DELETE SET NULL,

    CONSTRAINT chk_ficha_base_tipo
        CHECK (tipo_ficha IN (0, 1)),

    CONSTRAINT chk_ficha_base_status
        CHECK (status IN (0, 1))
);
-- rollback DROP TABLE IF EXISTS ficha_base;

-- changeset toswim:004-criar-index-ficha-base-usuario
-- comment: Cria index de busca de fichas por usuario
CREATE INDEX idx_ficha_base_usuario ON ficha_base (cod_usuario);
-- rollback DROP INDEX IF EXISTS idx_ficha_base_usuario;

-- changeset toswim:004-criar-trigger-ficha-base
-- comment: Cria trigger de atualizacao automatica do updated_at na tabela ficha_base
CREATE TRIGGER trg_ficha_base_updated_at
    BEFORE UPDATE ON ficha_base
    FOR EACH ROW
    EXECUTE FUNCTION fn_atualizar_updated_at();
-- rollback DROP TRIGGER IF EXISTS trg_ficha_base_updated_at ON ficha_base;