-- liquibase formatted sql

-- changeset toswim:005-criar-serie-ficha
-- comment: Cria a tabela de series da ficha base
CREATE TABLE serie_ficha (
    cod_serie_ficha       INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_ficha             INT         NOT NULL,
    ordem                 SMALLINT    NOT NULL,
    tipo_nado             SMALLINT    NOT NULL,
    quantidade_repeticoes INT         NOT NULL,
    distancia_m           INT         NOT NULL,
    tempo_pausa_seg       INT         NOT NULL,
    is_goal_series        BOOLEAN     NOT NULL DEFAULT FALSE,
    observacoes           TEXT        NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_serie_ficha_ficha
        FOREIGN KEY (cod_ficha)
        REFERENCES ficha_base (cod_ficha)
        ON DELETE CASCADE,

    CONSTRAINT uq_serie_ficha_ordem
        UNIQUE (cod_ficha, ordem),

    CONSTRAINT chk_serie_ficha_tipo_nado
        CHECK (tipo_nado IN (0, 1, 2, 3)),

    CONSTRAINT chk_serie_ficha_quantidade
        CHECK (quantidade_repeticoes > 0),

    CONSTRAINT chk_serie_ficha_distancia
        CHECK (distancia_m > 0),

    CONSTRAINT chk_serie_ficha_tempo_pausa
        CHECK (tempo_pausa_seg >= 0),

    CONSTRAINT chk_serie_ficha_ordem
        CHECK (ordem > 0)
);
-- rollback DROP TABLE IF EXISTS serie_ficha;

-- changeset toswim:005-criar-index-serie-ficha
-- comment: Cria index de busca de series por ficha
CREATE INDEX idx_serie_ficha_ficha ON serie_ficha (cod_ficha);
-- rollback DROP INDEX IF EXISTS idx_serie_ficha_ficha;

-- changeset toswim:005-criar-trigger-serie-ficha
-- comment: Cria trigger de atualizacao automatica do updated_at na tabela serie_ficha
CREATE TRIGGER trg_serie_ficha_updated_at
    BEFORE UPDATE ON serie_ficha
    FOR EACH ROW
    EXECUTE FUNCTION fn_atualizar_updated_at();
-- rollback DROP TRIGGER IF EXISTS trg_serie_ficha_updated_at ON serie_ficha;