-- liquibase formatted sql

-- changeset toswim:006-criar-meta
-- comment: Cria a tabela de metas de tempo do usuario
CREATE TABLE meta (
    cod_meta          INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_usuario       INT          NOT NULL,
    cod_serie_ficha   INT          NOT NULL,
    titulo_meta       VARCHAR(120) NOT NULL,
    tipo_nado         SMALLINT     NOT NULL,
    distancia_alvo_m  INT          NOT NULL,
    tempo_alvo_seg    INT          NOT NULL,
    pace_alvo_seg     INT          NOT NULL,
    modo_avaliacao    SMALLINT     NOT NULL DEFAULT 0,
    status            SMALLINT     NOT NULL DEFAULT 0,
    data_inicio       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    data_fim_prevista TIMESTAMPTZ  NULL,
    observacoes       TEXT         NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_meta_usuario
        FOREIGN KEY (cod_usuario)
        REFERENCES usuario (cod_usuario),

    CONSTRAINT fk_meta_serie_ficha
        FOREIGN KEY (cod_serie_ficha)
        REFERENCES serie_ficha (cod_serie_ficha)
        ON DELETE CASCADE,

    CONSTRAINT chk_meta_tipo_nado
        CHECK (tipo_nado IN (0, 1, 2, 3)),

    CONSTRAINT chk_meta_distancia
        CHECK (distancia_alvo_m > 0),

    CONSTRAINT chk_meta_tempo
        CHECK (tempo_alvo_seg > 0),

    CONSTRAINT chk_meta_pace
        CHECK (pace_alvo_seg > 0),

    CONSTRAINT chk_meta_modo_avaliacao
        CHECK (modo_avaliacao IN (0, 1, 2)),

    CONSTRAINT chk_meta_status
        CHECK (status IN (0, 1, 2))
);
-- rollback DROP TABLE IF EXISTS meta;

-- changeset toswim:006-criar-indexes-meta
-- comment: Cria indexes de busca da tabela meta
CREATE INDEX idx_meta_usuario ON meta (cod_usuario);
CREATE INDEX idx_meta_serie_ficha ON meta (cod_serie_ficha);
-- rollback DROP INDEX IF EXISTS idx_meta_usuario;
-- rollback DROP INDEX IF EXISTS idx_meta_serie_ficha;

-- changeset toswim:006-criar-trigger-meta
-- comment: Cria trigger de atualizacao automatica do updated_at na tabela meta
CREATE TRIGGER trg_meta_updated_at
    BEFORE UPDATE ON meta
    FOR EACH ROW
    EXECUTE FUNCTION fn_atualizar_updated_at();
-- rollback DROP TRIGGER IF EXISTS trg_meta_updated_at ON meta;