-- liquibase formatted sql

-- changeset toswim:007-criar-treino
-- comment: Cria a tabela de treinos executados
CREATE TABLE treino (
    cod_treino        INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_usuario       INT          NOT NULL,
    cod_ficha         INT          NOT NULL,
    titulo_treino     VARCHAR(120) NOT NULL,
    observacao        TEXT         NULL,
    distancia_total_m INT          NOT NULL DEFAULT 0,
    duracao_total_seg INT          NOT NULL DEFAULT 0,
    pace_medio_seg    INT          NULL,
    tamanho_piscina_m SMALLINT     NOT NULL,
    data_treino       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    status            SMALLINT     NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_treino_usuario
        FOREIGN KEY (cod_usuario)
        REFERENCES usuario (cod_usuario),

    CONSTRAINT fk_treino_ficha
        FOREIGN KEY (cod_ficha)
        REFERENCES ficha_base (cod_ficha),

    CONSTRAINT chk_treino_tamanho_piscina
        CHECK (tamanho_piscina_m IN (25, 50)),

    CONSTRAINT chk_treino_status
        CHECK (status IN (0, 1, 2)),

    CONSTRAINT chk_treino_distancia_total
        CHECK (distancia_total_m >= 0),

    CONSTRAINT chk_treino_duracao_total
        CHECK (duracao_total_seg >= 0),

    CONSTRAINT chk_treino_pace_medio
        CHECK (pace_medio_seg IS NULL OR pace_medio_seg > 0)
);
-- rollback DROP TABLE IF EXISTS treino;

-- changeset toswim:007-criar-indexes-treino
-- comment: Cria indexes de busca da tabela treino
CREATE INDEX idx_treino_usuario ON treino (cod_usuario);
CREATE INDEX idx_treino_ficha   ON treino (cod_ficha);
CREATE INDEX idx_treino_data    ON treino (data_treino DESC);
-- rollback DROP INDEX IF EXISTS idx_treino_usuario;
-- rollback DROP INDEX IF EXISTS idx_treino_ficha;
-- rollback DROP INDEX IF EXISTS idx_treino_data;

-- changeset toswim:007-criar-trigger-treino
-- comment: Cria trigger de atualizacao automatica do updated_at na tabela treino
CREATE TRIGGER trg_treino_updated_at
    BEFORE UPDATE ON treino
    FOR EACH ROW
    EXECUTE FUNCTION fn_atualizar_updated_at();
-- rollback DROP TRIGGER IF EXISTS trg_treino_updated_at ON treino;