-- liquibase formatted sql

-- changeset toswim:008-criar-serie-treino
-- comment: Cria a tabela de series executadas no treino
CREATE TABLE serie_treino (
    cod_serie_treino                INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_treino                      INT         NOT NULL,
    cod_serie_ficha                 INT         NULL,
    cod_meta                        INT         NULL,
    ordem                           SMALLINT    NOT NULL,
    tipo_nado                       SMALLINT    NOT NULL,
    quantidade_repeticoes_planejada INT         NOT NULL,
    distancia_planejada_m           INT         NOT NULL,
    tempo_pausa_seg                 INT         NOT NULL DEFAULT 0,
    tempo_total_seg                 INT         NULL,
    distancia_total_m               INT         NULL,
    pace_medio_seg                  INT         NULL,
    observacoes                     TEXT        NULL,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_serie_treino_treino
        FOREIGN KEY (cod_treino)
        REFERENCES treino (cod_treino)
        ON DELETE CASCADE,

    CONSTRAINT fk_serie_treino_serie_ficha
        FOREIGN KEY (cod_serie_ficha)
        REFERENCES serie_ficha (cod_serie_ficha)
        ON DELETE SET NULL,

    CONSTRAINT fk_serie_treino_meta
        FOREIGN KEY (cod_meta)
        REFERENCES meta (cod_meta)
        ON DELETE SET NULL,

    CONSTRAINT uq_serie_treino_ordem
        UNIQUE (cod_treino, ordem),

    CONSTRAINT chk_serie_treino_tipo_nado
        CHECK (tipo_nado IN (0, 1, 2, 3)),

    CONSTRAINT chk_serie_treino_quantidade
        CHECK (quantidade_repeticoes_planejada > 0),

    CONSTRAINT chk_serie_treino_distancia_planejada
        CHECK (distancia_planejada_m > 0),

    CONSTRAINT chk_serie_treino_tempo_pausa
        CHECK (tempo_pausa_seg >= 0),

    CONSTRAINT chk_serie_treino_ordem
        CHECK (ordem > 0),

    CONSTRAINT chk_serie_treino_tempo_total
        CHECK (tempo_total_seg IS NULL OR tempo_total_seg > 0),

    CONSTRAINT chk_serie_treino_distancia_total
        CHECK (distancia_total_m IS NULL OR distancia_total_m > 0),

    CONSTRAINT chk_serie_treino_pace_medio
        CHECK (pace_medio_seg IS NULL OR pace_medio_seg > 0)
);
-- rollback DROP TABLE IF EXISTS serie_treino;

-- changeset toswim:008-criar-indexes-serie-treino
-- comment: Cria indexes de busca da tabela serie_treino
CREATE INDEX idx_serie_treino_treino ON serie_treino (cod_treino);
CREATE INDEX idx_serie_treino_meta   ON serie_treino (cod_meta);
-- rollback DROP INDEX IF EXISTS idx_serie_treino_treino;
-- rollback DROP INDEX IF EXISTS idx_serie_treino_meta;

-- changeset toswim:008-criar-trigger-serie-treino
-- comment: Cria trigger de atualizacao automatica do updated_at na tabela serie_treino
CREATE TRIGGER trg_serie_treino_updated_at
    BEFORE UPDATE ON serie_treino
    FOR EACH ROW
    EXECUTE FUNCTION fn_atualizar_updated_at();
-- rollback DROP TRIGGER IF EXISTS trg_serie_treino_updated_at ON serie_treino;