-- liquibase formatted sql

-- changeset toswim:009-criar-repeticao-serie-treino
-- comment: Cria a tabela de repeticoes individuais de cada serie executada
CREATE TABLE repeticao_serie_treino (
    cod_repeticao_serie_treino INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_serie_treino           INT         NOT NULL,
    numero_repeticao           SMALLINT    NOT NULL,
    distancia_real_m           INT         NOT NULL,
    duracao_seg                INT         NOT NULL,
    pace_seg                   INT         NULL,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_repeticao_serie_treino_serie
        FOREIGN KEY (cod_serie_treino)
        REFERENCES serie_treino (cod_serie_treino)
        ON DELETE CASCADE,

    CONSTRAINT chk_repeticao_numero
        CHECK (numero_repeticao > 0),

    CONSTRAINT chk_repeticao_distancia
        CHECK (distancia_real_m > 0),

    CONSTRAINT chk_repeticao_duracao
        CHECK (duracao_seg > 0),

    CONSTRAINT chk_repeticao_pace
        CHECK (pace_seg IS NULL OR pace_seg > 0),

    CONSTRAINT uq_repeticao_serie_numero
        UNIQUE (cod_serie_treino, numero_repeticao)
);
-- rollback DROP TABLE IF EXISTS repeticao_serie_treino;

-- changeset toswim:009-criar-index-repeticao-serie-treino
-- comment: Cria index de busca de repeticoes por serie
CREATE INDEX idx_repeticao_serie ON repeticao_serie_treino (cod_serie_treino);
-- rollback DROP INDEX IF EXISTS idx_repeticao_serie;