-- liquibase formatted sql

-- changeset toswim:010-criar-treino-meta
-- comment: Cria a tabela de vinculo entre treino e meta
CREATE TABLE treino_meta (
    cod_treino_meta  INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_treino       INT         NOT NULL,
    cod_meta         INT         NOT NULL,
    cod_serie_treino INT         NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_treino_meta_treino
        FOREIGN KEY (cod_treino)
        REFERENCES treino (cod_treino)
        ON DELETE CASCADE,

    CONSTRAINT fk_treino_meta_meta
        FOREIGN KEY (cod_meta)
        REFERENCES meta (cod_meta)
        ON DELETE CASCADE,

    CONSTRAINT fk_treino_meta_serie_treino
        FOREIGN KEY (cod_serie_treino)
        REFERENCES serie_treino (cod_serie_treino)
        ON DELETE SET NULL
);
-- rollback DROP TABLE IF EXISTS treino_meta;

-- changeset toswim:010-criar-indexes-treino-meta
-- comment: Cria indexes de busca e unicidade da tabela treino_meta
CREATE INDEX idx_treino_meta_treino ON treino_meta (cod_treino);
CREATE INDEX idx_treino_meta_meta   ON treino_meta (cod_meta);

-- Impede duplicata quando a serie esta definida
CREATE UNIQUE INDEX uq_treino_meta_com_serie
    ON treino_meta (cod_treino, cod_meta, cod_serie_treino)
    WHERE cod_serie_treino IS NOT NULL;

-- Impede duplicata quando o vinculo e apenas com o treino
CREATE UNIQUE INDEX uq_treino_meta_sem_serie
    ON treino_meta (cod_treino, cod_meta)
    WHERE cod_serie_treino IS NULL;
-- rollback DROP INDEX IF EXISTS idx_treino_meta_treino;
-- rollback DROP INDEX IF EXISTS idx_treino_meta_meta;
-- rollback DROP INDEX IF EXISTS uq_treino_meta_com_serie;
-- rollback DROP INDEX IF EXISTS uq_treino_meta_sem_serie;